### ISSUE TITLE
[Question] "case" vs "caseid" as field name to create case object

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#109]
Please fill out the following details:

1. Version of Mobile SDK Used:  214.0.2Live agent chat version: 3.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: Android 9
4. Device: Google Pixel 2 XL
5. Steps to reproduce: 
1. Customer with existing account in Salesforce initiate chat from Android device. Chat is routed to Agent A
2. From Agent A side, Live Chat Transcript 01 is created, Case 01 is popped up next to Live chat transcript chat. Live Chat Transcript 01 is automatically associated with Case 01
3. Agent ends the chat.
4. The same customer initiate another chat from Android device.
5. Chat is routed to Agent B
6. From Agent side, Live Chat Transcript 02 is created, Case 01 is popped up next to Live chat transcript chat. Live Chat Transcript 02 is ALSO associated with Case 01

6. Actual behavior:  Live Chat Transcript initiated by the same customer is added to the same existing case.
7. Expected Behavior:When a new chat session is initiated (Live Chat Transcript02), it should always create a new case (Case 02) and associate Live Chat transcript to it.
8. Error Log: 
9. Additional Info: 
Version of your developer tool: Android Studio 3.2
What language they are using: Kotlin 

------------------------------------------------------------------------

We've implemented the resolution in the previously raised case  #101 
It was working fine in UAT environment but the issue still persists when we move to Production, the case creation only works for some users. 

Our developer suspects that it could be because we're using "caseid" as field name instead of "case" to create new case. And the mismatched keyword intefere with the case creation process.
But since we can't test and reproduce in UAT environment, we would like to check:
1) Could this be the cause? Any other possible causes? 
2) Would changing field name from "caseid" to "case" cause any serious problem? would there be any implications. 

Thank you!

**Comment by rileymacdonald-sf** [comment]
@JinTiloganart It's difficult to confirm if the field name you're using is causing this issue. This type of problem is generally due to a configuration errors. Is it possible for you to send us a code snippet for the entities setup and from that explain the behavior you're expecting?

I've updated the code at https://github.com/rileymacdonald-sf/ServiceSDK-Android/blob/riley/case_creation_test/Examples/SnapinsSDKExample/app/src/kotlinImplDebug/java/com/salesforce/snapinssdkexample/utils/ServiceSDKUtils.kt#L44 and verified it's working for automatic case creation using Kotlin. You can checkout this code and insert your entity setup code into the  `getChatConfigurationBuilder` function for further testing.

Thanks

**Comment by JinTiloganart** [comment]
Hi @rileymacdonald-sf 
I've attached the code for generating cases in this comment. Please let me know if you need further information. 
[salesforce_android.docx](https://github.com/forcedotcom/ServiceSDK-Android/files/2651536/salesforce_android.docx)

Also, just to clarify, when I said 'we can't reproduce the issue in UAT' I meant our team didn't run into this problem while testing, perhaps it's because our sample group was too small, so the issue only occurs in Live environment.

> This type of problem is generally due to a configuration errors. 
Any other possible causes? 

Thanks

>
