### ISSUE TITLE
[Questions] Session will timeout soon notification

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#127]
In iOS, chat can send a notification to user when session is about to time out, but we can't seem to find this ability in Android document, can you help us check/confirm on this?
![image](https://user-images.githubusercontent.com/44631258/53400674-581d7700-39e9-11e9-9217-85825287a79c.png)

**Comment by colinmacdonald** [comment]
@JinTiloganart This is a platform difference between Android and iOS. On iOS the session cannot be kept alive while in the background due to limitations in what can be done while backgrounded. This timeout is a local notification on the device, which is used to bring the end user back to the app so the session doesn't die. On Android we are capable of making the network requests to the server to keep the session alive even while the app is backgrounded making this notification unnecessary. We should make this clear in the documentation, I've made a note of this gap. Thank you!
