### ISSUE TITLE
Receive double push notifications

### ISSUE THREAD

**Issue by boymustafa** [forcedotcom/ServiceSDK-Android#71]
We have implemented firebase SDK and received push notification correctly. However, when implementing the Salesforce Snaps-In SDK, we started to received duplicate push notification message. Only when we removed the whole SDK then the issue no longer happen.
We used servicesdk:210.0.0

We are aware that the SDK doesn't support FCM for now. But is there a way we can disable specifically the SDK push notification while still retain the salesforce live chat functionality?

**Comment by evanisnor** [comment]
Hi @boymustafa ! We have had 4 releases since our 210 release. Please refer to the [releases  page](https://github.com/forcedotcom/ServiceSDK-Android/releases) for the release notes and our [setup guide](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_install_sdk.htm#ess_sdk_setup_android) to update your app to the latest version of the SDK. If you only require the Live Agent Chat functionality, we recommend using the following `chat-ui` dependency in your gradle script, which does not include any dependencies on GCM or FCM.

```
implementation "com.salesforce.service:chat-ui:3.1.0"
```

Cheers!

**Comment by boymustafa** [comment]
thanks for the help @evanisnor
