### ISSUE TITLE
Hidden fields show empty view before chat bubble opens

### ISSUE THREAD

**Issue by arlindiDev** [forcedotcom/ServiceSDK-Android#82]
I want to send hidden fields to my salesforce organisation but when I open the Chat UI first a Dialog/View is shown which is bad for the UX, see below:

I am adding the hidden fields as the documentation describes with `ChatUserData` in the salesforce backend I can see the fields correctly but why is this view showing which is bad UX is this default behaviour of the SDK or can I change this?

![salesforce](https://user-images.githubusercontent.com/6221337/44733757-8aa4f080-aae8-11e8-94fe-bf240d1d771d.png)

**Comment by evanisnor** [comment]
Hey @arlindiDev, thanks for posting. You can turn this pre-chat UI off in your `ChatUIConfiguration` since you don't have any pre-chat fields to display.

```
new ChatUIConfiguration.Builder()
    .disablePreChatView(true)
    <other options>
    .build()
```

http://forcedotcom.github.io/ServiceSDK-Android/releases/chat/3.1.0/api/reference/com/salesforce/android/chat/ui/ChatUIConfiguration.Builder.html#disablePreChatView(boolean)

I hope this helps!
Cheers,
Evan

**Comment by arlindiDev** [comment]
Thank you that works :)
